name: Run E2E Tests

on: [pull_request_target]

permissions:
  contents: read

jobs:
  e2e:
    name: E2E tests on ${{ matrix.browser }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]
    env:
      WXT_CI: true
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: '.bun-version'
      - uses: actions/setup-node@v4
      - run: bun install --frozen-lockfile --prefer-offline
      - run: bun ${{ matrix.browser == 'chrome' && 'e2e' || 'e2e:firefox' }}
